FROM golang:1.18.2-alpine3.14 as builder
RUN apk update && apk add alpine-sdk git && rm -rf /var/cache/apk/*
RUN mkdir -p /api
WORKDIR /api

COPY go.mod .
COPY go.sum . 
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./build/devhub ./src/main.go



FROM alpine:latest
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
RUN mkdir -p /api
WORKDIR /api
ENV GIN_MODE=release
COPY --from=builder /api/build/devhub .
COPY --from=builder /api/.env-prod .
EXPOSE 8080 8080

ENTRYPOINT ["./devhub"]